<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Hapus</name>
   <tag></tag>
   <elementGuidId>81781d08-193a-4269-aeea-ae3428c7a20a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;promo Hapus&quot;i] >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>54c6827e-f486-4058-a244-cfa43207085b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b8bd3a53-a8ff-4474-8fef-deb908a29a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn rounded-pill btn-primary-600 radius-8 px-20 py-11 d-flex align-items-center</value>
      <webElementGuid>07c302f3-b768-4ca2-949a-aee44e9ae079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                         Hapus
                                                    </value>
      <webElementGuid>2b94c520-98f1-4080-b09b-027588699094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pills-all&quot;)/div[@class=&quot;row gy-4&quot;]/div[@class=&quot;col-xxl-3 col-md-4 col-sm-6&quot;]/a[1]/div[@class=&quot;hover-scale-img border radius-16 overflow-hidden&quot;]/div[@class=&quot;py-16 px-24&quot;]/form[1]/button[@class=&quot;btn rounded-pill btn-primary-600 radius-8 px-20 py-11 d-flex align-items-center&quot;]</value>
      <webElementGuid>c9f20772-8ec8-406e-bc54-aeed018f230c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[3]</value>
      <webElementGuid>91905f83-e879-4608-9d96-246e2139b747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pills-all']/div/div[2]/a/div/div[2]/form/button</value>
      <webElementGuid>204655f8-6a52-4554-bd01-cd1001e5767b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promo'])[2]/following::button[2]</value>
      <webElementGuid>301bd8a8-8836-4fa6-94be-4097b7e3b3a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/div/div[2]/form/button</value>
      <webElementGuid>2265afe7-07a4-4912-b286-38545106fb9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
                                                         Hapus
                                                    ' or . = '
                                                         Hapus
                                                    ')]</value>
      <webElementGuid>ac4668f3-1163-4f68-be90-0f3225bbf268</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
