<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iconify-icon_Bundle_icon-l Admin-af0</name>
   <tag></tag>
   <elementGuidId>fe0d11da-507a-461b-80f0-34d492e5bd62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[2]/iconify-icon</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.sidebar-mobile-toggle > iconify-icon.icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iconify-icon</value>
      <webElementGuid>a1062836-2c38-4c91-9fa5-0eafb4c69944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>icon</name>
      <type>Main</type>
      <value>heroicons:bars-3-solid</value>
      <webElementGuid>6d8c0b62-a61d-4d97-b861-459459909b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>44ac562a-89ed-4824-bedb-976b6222a172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[@class=&quot;dashboard-main&quot;]/div[@class=&quot;navbar-header&quot;]/div[@class=&quot;row align-items-center justify-content-between&quot;]/div[@class=&quot;col-auto&quot;]/div[@class=&quot;d-flex flex-wrap align-items-center gap-4&quot;]/button[@class=&quot;sidebar-mobile-toggle&quot;]/iconify-icon[@class=&quot;icon&quot;]</value>
      <webElementGuid>ea99edd0-de02-4a1a-ae2d-3f09e4b06ad6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/iconify-icon</value>
      <webElementGuid>37c08c2b-7e82-4389-a36c-acb728964aaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
